version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    groups:
      frontend-minor-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 维护（前端依赖）

  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    groups:
      backend-minor-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 维护（后端依赖）

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 维护（工作流依赖）
